package ir.co.sadad.cartollapi.service;

import ir.co.sadad.cartollapi.dtos.*;

public interface NajiService {

    /**
     * <p>
     * First of all uses Shahkar and otp services => based on ownerNationalCode and ownerCellphone,
     * and otp used for sending msg for plate owner cellphone
     * Inserts a record into user table(based on ssn and cellPhone params,
     * if not exist) and into plate table (if not exist), and a record into userPlate,
     * which means login user can add plate information of others into her/his baam
     * </p>
     *
     * @param request
     * @param ssn       generated by gateway
     * @param cellphone generated by gateway
     * @return
     */
    PlateCreateResponseDto create(PlateCreateRequestDto request, String ssn, String cellphone);

    /**
     * This service gets a list of plates which inserted by who logins (ssn owner)
     *
     * @param ssn generated by gateway
     * @return
     */
    PlateSearchResponseDto getPlates(String ssn);

    /**
     * This method deletes plate of userPlate table, while the plate information will be remain in plate table
     *
     * @param plateNo
     * @param ssn generated by gateway
     * @return
     */
    PlateDeleteResponseDto deletePlate(String plateNo, String ssn);

    /**
     * gets plateNo and if exists for this login's user (ssn owner), then Just updates optional fields, such as plateName, barcode, vin for CAR and motorNumber for MOTORCYCLE
     *
     * @param updateRequest
     * @param ssn generated by gateway
     * @return
     */
    PlateUpdateResponseDto updatePlate(PlateUpdateRequestDto updateRequest, String ssn);

//    /**
//     * <p>
//     * for inquiry of Naji (khalafi), first sends sms to plateOwner, if was success then will be pay the wage (5200 toman)
//     * after taht result of inquiry will be show.
//     * If we pay wage but the inquiry result wan not success, we save oru payment number in debitCount field
//     * so, for next inquiry don't need to pay again.
//     * </p>
//     *
//     * @param request
//     * @param ssn
//     * @param authToken
//     * @return
//     */
//    SadadNajiDto.ViolationAggregation inquiryAggregationNaji(NajiInquiryDto.Request request, String ssn, String authToken);

    ViolationInquiryResponseDto getInquiryResults(String ssn);

    void setInquiryStatus(String ssn, String paymentId, String paperId);
}
